### ISSUE TITLE
Crash on Android 7.0 (preview)

### ISSUE THREAD

**Issue by Avinash-Bhat** [BlinkID/blinkid-android#10]
The sdk (demo app) crashes with the following logs

```
08-22 15:26:20.227 17684-17843/com.microblink.blinkid W/linker: library "/system/lib/libui.so" ("/system/lib/libui.so") needed or dlopened by "/data/app/com.microblink.blinkid-1/lib/arm/libBlinkID.so" is not accessible for the namespace "classloader-namespace" - the access is temporarily granted as a workaround for http://b/26394120, note that the access will be removed in future releases of Android.
08-22 15:26:20.244 17684-17843/com.microblink.blinkid E/linker: library "/system/lib/hw/gralloc.msm8084.so" ("/system/lib/hw/gralloc.msm8084.so") needed or dlopened by "/system/lib/libhardware.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.microblink.blinkid-1/lib/arm:/system/fake-libs:/data/app/com.microblink.blinkid-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.microblink.blinkid"]
08-22 15:26:20.244 17684-17843/com.microblink.blinkid E/HAL: load: module=/system/lib/hw/gralloc.msm8084.so
                                                             dlopen failed: library "/system/lib/hw/gralloc.msm8084.so" needed or dlopened by "/system/lib/libhardware.so" is not accessible for the namespace "classloader-namespace"
08-22 15:26:20.244 17684-17843/com.microblink.blinkid E/GraphicBufferMapper: FATAL: can't find the gralloc module
08-22 15:26:20.245 17684-17843/com.microblink.blinkid E/linker: library "/system/lib/hw/gralloc.msm8084.so" ("/system/lib/hw/gralloc.msm8084.so") needed or dlopened by "/system/lib/libhardware.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.microblink.blinkid-1/lib/arm:/system/fake-libs:/data/app/com.microblink.blinkid-1/base.apk!/lib/armeabi-v7a", permitted_paths="/data:/mnt/expand:/data/data/com.microblink.blinkid"]
08-22 15:26:20.245 17684-17843/com.microblink.blinkid E/HAL: load: module=/system/lib/hw/gralloc.msm8084.so
                                                             dlopen failed: library "/system/lib/hw/gralloc.msm8084.so" needed or dlopened by "/system/lib/libhardware.so" is not accessible for the namespace "classloader-namespace"
08-22 15:26:20.245 17684-17843/com.microblink.blinkid E/GraphicBufferAllocator: FATAL: can't find the gralloc module
08-22 15:26:20.245 17684-17843/com.microblink.blinkid A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x40 in tid 17843 (Recognition)
                                                              
                                                              [ 08-22 15:26:20.245   270:  270 W/         ]
                                                              debuggerd: handling request: pid=17684 uid=10321 gid=10321 tid=17843
```

I think using gralloc is not allowed anymore.

**Comment by DoDoENT** [comment]
On which device does this happen?

**Comment by DoDoENT** [comment]
Is it maybe Nexus 6? If yes, then this bug is already fixed in our codebase and will be part of our next release.

**Comment by Avinash-Bhat** [comment]
Yes, in Nexus 6 android 7.0 (NPD90G).

BTW, any ETA?

**Comment by i1E** [comment]
Hi @Avinash-Bhat,

SDK with this fix will be released today.

**Comment by DoDoENT** [comment]
Hi @Avinash-Bhat,

BlinkID v2.9.0 has been released. If this error is now fixed for you, please close this issue.

**Comment by Avinash-Bhat** [comment]
Will check and confirm

Thx for the fix 👍

**Comment by Avinash-Bhat** [comment]
working with v2.9.0

**Comment by NaneNare** [comment]
The issue is actual for me:
device: N

- exus 9
- os: Android 7
- build: NRD90R

`java.lang.UnsatisfiedLinkError: dlopen failed: library "libui.so" not found
                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                                  at java.lang.System.loadLibrary(System.java:1530)`

**Comment by DoDoENT** [comment]
@NaneNare, this crash seems different than one reported initially. Please open a new issue for it, and state whether BlinkID worked on Nexus 9 before upgrading it to Android 7.

**Comment by vipinbnk** [comment]
The below error still happening in 6.2.0 for x86 devices.

```
`error loading native library
java.lang.UnsatisfiedLinkError: dlopen failed: library
"libBlinkID.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:9)
                                                                                                    	at com.microblink.blinkid.hardware.MicroblinkDeviceManager.<clinit>(line:35)
                                                                                                    	at com.microblink.blinkid.hardware.MicroblinkDeviceManager.IllIIIIllI(line:1)
                                                                                                    	at com.microblink.blinkid.secured.lIlIllllII.IllIIIllII(line:3)
                                                                                                    	at com.microblink.blinkid.secured.lIlIllllII.llIIlIlIIl(line:1)
                                                                                                    	at com.microblink.blinkid.MicroblinkSDK.<clinit>(line:1)
                                                                                                    	at com.microblink.blinkid.MicroblinkSDK.setLicenseKey(Unknown Source:0)
```

**Comment by MBrizic01** [comment]
hi @vipinbnk, please check our [GitHub](https://github.com/BlinkID/blinkid-android?tab=readme-ov-file#processor-architecture) page for the device requirements. The support for x86 and x86_64 has been removed in BlinkID v6.0.
