### ISSUE TITLE
com.microblink.recognition.InvalidLicenceKeyException

### ISSUE THREAD

**Issue by KavyaHarisha** [BlinkID/blinkid-android#110]
MicroblinkSDK.setLicenseFile("blink_id.mblic", this);

Above the line, I am getting below issue.

Caused by: com.microblink.recognition.InvalidLicenceKeyException: License buffer signature verification failed!
Advance Thanks to solving the issue.

**Comment by DoDoENT** [comment]
Hi @KavyaHarisha, can you please tell whether the demo app works with original demo license key? Also, what account have you used to generate the license key? I am not able to find the user with name Kavya Harisha in our license management system.

**Comment by KavyaHarisha** [comment]
I have not generated the license key. Someone generated and that license
file I am using.

**Comment by DoDoENT** [comment]
Well, the generated license is obviously invalid. Please, register at [Microblink Developer Dashboard](https://microblink.com/login) and create a free trial license for your app. If the generated trial license does not work, please report that as a bug.

**Comment by KavyaHarisha** [comment]
Ok, I will try with the trial version.

**Comment by KavyaHarisha** [comment]
Yeah, I tried with the trial version. Thank you for the help.
But I am facing another problem that is:
I added below two lines in oncreate of MainActivity.

mRecognizer = new MrtdRecognizer();
mRecognizerBundle = new RecognizerBundle(mRecognizer);

Here I am getting below issue.

Process: com.licenceinformation, PID: 13140
    java.lang.UnsatisfiedLinkError: No implementation found for long
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.nativeConstruct()
(tried
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct
and
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct__)
        at
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.nativeConstruct(Native
Method)
        at
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.<init>(line:225)
        at
com.licenceinformation.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:7036)
        at android.app.Activity.performCreate(Activity.java:7027)
        at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I am using the latest version of Blink Id: 4.0
Could you please help me here.

**Comment by DoDoENT** [comment]
Hi @KavyaHarisha, the UnsatisfiedLinkError is caused by failure to load native libraries that are required for BlinkID.

Which device are you using for testing? Does the unchanged sample app work on that same device? Does the APK with your app contain all native libraries that are required? You can check that by unzipping your APK and checking the contents of the lib folder.

For more information about native library requirements in BlinkID, please read [this article](https://github.com/blinkid/blinkid-android#archConsider).

**Comment by KavyaHarisha** [comment]
Hey, actually I am running in the mobile device, not an emulator.
My mobile was: One plus 3.
Version 8.0(Oreo)
I check my device is support for recognition process, it says it supports.
Then after I has to do anything?
The above article link for emulator libraries.
Could you please clarify me what i have do?

**Comment by KavyaHarisha** [comment]
Your sample code was running perfectly in my mobile device, but when trying
to integrate into my project I am getting an error.

**Comment by DoDoENT** [comment]
> Your sample code was running perfectly in my mobile device, but when trying
to integrate into my project I am getting an error.

This indicates that your project either uses native libraries or depends on some 3rd party library that also uses native libraries and does not provide binaries for arm64.

You can unzip the APK of your app and check the contents of the `lib` folder. It should contain folders `armeabi-v7a`, `arm64-v8a`, `x86` and `x86_64`. All those folders should contain same number of `.so` files with same names. The `libBlinkID.so` is file from BlinkID SDK. Other files are there from either your native code or 3rd party libraries that you use.

In your case some of those other files are missing in `arm64-v8a` folder, as some of your third party library does not provide support for `arm64-v8a` - you will observe that in folder `arm64-v8a` some files are missing, that are probably available in `armeabi-v7a`. If that is true, then your app will work on old 32-bit android ARM devices, but not on modern 64-bit devices. In that case, you can force your app to always use 32-bit mode, as described in article I've linked before, or you can contact the provider of your 3rd party library and ask them to add support for modern 64-bit android devices.

**Comment by KavyaHarisha** [comment]
I unchecked my APK file, I found all the file what mentioned in the above
response.
Please check the attachment.
Then next to what I have to do?

**Comment by DoDoENT** [comment]
Your attachment is not visible. Which file is missing?

**Comment by KavyaHarisha** [comment]
Oops, Now it's visible, could you please check now.

**Comment by DoDoENT** [comment]
Your attachment is still not visible. Please provide a link to it.

**Comment by KavyaHarisha** [comment]
Fine, here is the link.
https://drive.google.com/file/d/1bRsDDKwGxW6uRRzLj2yiWXcRuXJLAfth/view?usp=sharing
.
Sorry once again.

**Comment by DoDoENT** [comment]
OK, this indicates that all native libraries are present and OK. Can you attach the entire ADB log prior crash? There is probably something else preventing the native library from being loaded...

**Comment by KavyaHarisha** [comment]
These are the below lines, what I am getting an error.
Please visit it.

06-22 19:58:34.677 17702-17702/com.licenceinformation I/InstantRun:
starting instant run server: is main process
06-22 19:58:34.698 17702-17702/com.licenceinformation E/zygote64: No
implementation found for long
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.nativeConstruct()
(tried
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct
and
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct__)
06-22 19:58:34.698 17702-17702/com.licenceinformation D/AndroidRuntime:
Shutting down VM


    --------- beginning of crash
06-22 19:58:34.700 17702-17702/com.licenceinformation E/AndroidRuntime:
FATAL EXCEPTION: main
    Process: com.licenceinformation, PID: 17702
    java.lang.UnsatisfiedLinkError: No implementation found for long
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.nativeConstruct()
(tried
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct
and
Java_com_microblink_entities_recognizers_blinkid_mrtd_MrtdRecognizer_nativeConstruct__)
        at
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.nativeConstruct(Native
Method)
        at
com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer.<init>(line:225)
        at
com.licenceinformation.MainActivity.createOverlay(MainActivity.java:77)
        at com.licenceinformation.MainActivity.<init>(MainActivity.java:35)
        at java.lang.Class.newInstance(Native Method)
        at
android.app.Instrumentation.newActivity(Instrumentation.java:1191)
        at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
        at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-22 19:58:34.703 17702-17702/com.licenceinformation W/OPDiagnose:
getService:OPDiagnoseService NULL
06-22 19:58:34.705 17702-30734/com.licenceinformation D/OSTracker: OS
Event: crash
06-22 19:58:34.710 17702-17702/com.licenceinformation I/Process: Sending
signal. PID: 17702 SIG: 9

**Comment by DoDoENT** [comment]
This log seems incomplete. Is this really everything that was outputted into ADB log? If yes, then please create a minimal project that reproduces the issue. You can start with our official sample app, for which you stated that works correctly, and add minimal changes to it that will reproduce the same crash you have in your app. Then, please send that minimal sample project to us so we can help you with the crash.

**Comment by DoDoENT** [comment]
Your sample application attachment is missing. Please use the link sharing as before.

**Comment by KavyaHarisha** [comment]
I do not send any attachment, in the previous mail,
If you want here you go by using below link:
https://drive.google.com/file/d/1RAkjsdy-Qa-ucheZolny3Qg2gLfHga2G/view?usp=sharing
.

**Comment by DoDoENT** [comment]
The problem is that your `MyApplication.java` is not registered in your `AndroidManifest.xml`, so it is not being executed and therefore it is not setting the license nor loading the native library.

Please make sure that `android:name` attribute in your manifest's `application` tag has a path to `MyApplication` class, like this:

```xml
    <application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
```

We will update the SDK to make a better error in cases like yours. The error should have been "InvalidLicenseKey", a not "UnsatisfiedLinkError".

If this has solved your problem, please close the issue.

**Comment by KavyaHarisha** [comment]
Thank you for your to help to resolve my issue.

**Comment by KavyaHarisha** [comment]
Hi, 
My application was crashing due to below error :
Caused by: com.microblink.recognition.InvalidLicenceKeyException: Please set valid license key before creating RecognizerRunnerView
        at com.microblink.view.recognition.RecognizerRunnerView.IIlIIlIllI(line:131)
        at com.microblink.view.recognition.RecognizerRunnerView.<init>(line:125)
        at com.microblink.fragment.RecognizerRunnerFragment.onCreateView(line:165)
        at android.app.Fragment.performCreateView(Fragment.java:2508)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreate(Activity.java:7047)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)

Is it possible to handle this exception, without crashing the application?
I want to handle that exception, could you please help me here.

Advance Thank you.

**Comment by i1E** [comment]
Hi @KavyaHarisha,

why do you want to handle the InvalidLicenceKeyException? There is no point in handling this exception because our library does not work if you don't have a valid license key. Please obtain valid license key from [Microblink dashboard](https://microblink.com/login).

[Here](https://github.com/BlinkID/blinkid-android#-performing-your-first-scan) is the code snippet that shows how to set license key.

 If you have any other problems with the license key, please contact us again.

**Comment by KavyaHarisha** [comment]
Yes, I can understand without the license key, Blink Id will not work.
Here instead of app crashing showing an alert dialog or toast message to handle the exception is the best way right (I think)?

**Comment by KavyaHarisha** [comment]
Ok fine and thank you for more given information.

**Comment by arishanapalli** [comment]
Terminating app due to uncaught exception 'MBInvalidLicenseKeyException', reason: 'Your license key is invalid! License buffer signature verification failed!'

how to handle if license is invalid or expired in swift 4.2! 
How to handle for incense key is invalid? ios side.

```
        do
        {
            MBMicroblinkSDK.sharedInstance().setLicenseResource("license", withExtension: "txt", inSubdirectory: "", for: Bundle.main)
        }
        catch let error as NSError
        {
            print(error.localizedDescription)
            // write some code to recover from error
        }
        catch let error // as Error - "'as' test is always true"
        {
            print(error.localizedDescription)
            // write some code to recover from error
        }
```

Please let me know the best way to handle license key related crashes!

**Comment by Brankacro** [comment]
Hello @arishanapalli,

This looks like the license key expired.
Can you please share the license key that you are using in your app?

Also, the next time if the issue like this occurs, I suggest to contact us directly at support@microblink.com for quicker issue resolution. We can also continue this conversation over email.
Kind regards.

Branka

**Comment by NaeemUOSdev** [comment]
i am using the same key and and same package name in  my application still getting this exception:
  Process: blinkdemo.coo, PID: 18061
                                                                                                    java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:473)
                                                                                                    	at android.view.View.performClick(View.java:7575)
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
                                                                                                    	at android.view.View.performClickInternal(View.java:7531)
                                                                                                    	at android.view.View.access$3900(View.java:842)
                                                                                                    	at android.view.View$PerformClick.run(View.java:28866)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:264)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8312)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:468)
                                                                                                    	at android.view.View.performClick(View.java:7575) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7531) 
                                                                                                    	at android.view.View.access$3900(View.java:842) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28866) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:264) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8312) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) 
                                                                                                    Caused by: com.microblink.blinkid.licence.exception.InvalidLicenceKeyException: This entity is not allowed by currently active license!
                                                                                                    	at com.microblink.blinkid.entities.recognizers.blinkid.generic.BlinkIdMultiSideRecognizer.nativeConstruct(Native Method)
                                                                                                    	at com.microblink.blinkid.entities.recognizers.blinkid.generic.BlinkIdMultiSideRecognizer.<init>(line:2)
                                                                                                    	at com.microblink.blinkid.activity.result.contract.TwoSideDocumentScan.createIntent(line:2)
                                                                                                    	at com.microblink.blinkid.activity.result.contract.TwoSideDocumentScan.createIntent(line:1)
                                                                                                    	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:201)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
                                                                                                    	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
                                                                                                    	at blinkdemo.coo.MainActivity.onScanButtonClick(MainActivity.kt:22)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:468) 
                                                                                                    	at android.view.View.performClick(View.java:7575) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7531) 
                                                                                                    	at android.view.View.access$3900(View.java:842) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28866) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loop(Looper.java:264) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8312) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by NaeemUOSdev** [comment]
Unable to do remote licence check. why this exception is coming help me someone please

**Comment by Brankacro** [comment]
Hi @NaeemUllah121 
Thank you for reaching out. Could you please let us know the license key number of the license you are using (for example:LIC01000050831), the version of the SDK that you are using, and what document you are trying to scan?
Feel free to contact us at support@microblink.com for direct communication so we could see in detail your use case. Best.

**Comment by NaeemUOSdev** [comment]
LIC0100057252

**Comment by Brankacro** [comment]
Thank you @NaeemUllah121. Since we are in direct communication regarding your issue, we'll be closing this thread. Best.

**Comment by NaeemUOSdev** [comment]
Ok, thank you.
