### ISSUE TITLE
Exception after calling recognizerBundle.loadFromIntent(intent)

### ISSUE THREAD

**Issue by aednlaxer** [BlinkID/blinkid-android#118]
Hello.

I've been implementing a driver license scanner using `DetectorRecognizer`. After migrating from SDK 3 to SDK 4 I'm not able to get data from the resulting intent. When scanning is completed, result code is `Activity.RESULT_OK`.

Code where scanner is initialized:
```kotlin
dlScanner = DriverLicenseFrontSide()
recognizerBundle = RecognizerBundle(dlScanner.recognizer)
recognizerBundle.setAllowMultipleScanResultsOnSingleImage(false)
settings = DocumentUISettings(recognizerBundle)
settings.setUsingFlagSecure(true)
```

From `onActivityResult` I'm trying to load `intent` to `recognizerBundle`:
```kotlin
try {
    Log.d("DL scanner", "Exists in intent: ${recognizerBundle.existsInIntent(intent)}")
    Log.d("DL scanner", "Recognizer: ${dlScanner.recognizer}")
    Log.d("DL scanner", "Recognizer result: ${dlScanner.recognizer.result}")
    Log.d("DL scanner", "Recognizer detector: ${dlScanner.recognizer.detector}")
    Log.d("DL scanner", "Detector result ${dlScanner.recognizer.detector.result}")
    Log.d("DL scanner", "TemplatingClass: ${dlScanner.recognizer.result.templatingClass}")

    recognizerBundle.loadFromIntent(intent)
  } catch (e: Exception) {
    Log.e("DL scanner", "Exception! ", e)
  }
```

It gives this output:
```java
DL scanner: Exists in intent: true
DL scanner: Recognizer: com.microblink.entities.recognizers.detector.DetectorRecognizer@7a04f1a
DL scanner: Recognizer result: com.microblink.entities.recognizers.detector.DetectorRecognizer$Result@f77ca4b
DL scanner: Recognizer detector: com.microblink.entities.detectors.quad.document.DocumentDetector@6a62c28
DL scanner: Detector result Quadrilateral{mUpperLeft=Point{mX=0.0, mY=0.0}, mUpperRight=Point{mX=0.0, mY=0.0}, mLowerLeft=Point{mX=0.0, mY=0.0}, mLowerRight=Point{mX=0.0, mY=0.0}}
DL scanner: TemplatingClass: null

DL scanner: Exception! 
java.lang.RuntimeException: bad array lengths
    at android.os.Parcel.readTypedArray(Parcel.java:2266)
    at com.microblink.entities.recognizers.templating.TemplatingClass.<init>(line:200)
    at com.microblink.entities.recognizers.templating.TemplatingClass.<init>(line:15)
    at com.microblink.entities.recognizers.templating.TemplatingClass$1.createFromParcel(line:217)
    at com.microblink.entities.recognizers.templating.TemplatingClass$1.createFromParcel(line:214)
    at android.os.Parcel.readTypedArray(Parcel.java:2260)
    at com.microblink.entities.recognizers.templating.TemplatingRecognizer.readFromParcel(line:92)
    at com.microblink.entities.Entity.<init>(line:37)
    at com.microblink.entities.recognizers.Recognizer.<init>(line:21)
    at com.microblink.entities.recognizers.templating.TemplatingRecognizer.<init>(line:25)
    at com.microblink.entities.recognizers.detector.DetectorRecognizer.<init>(line:158)
    at com.microblink.entities.recognizers.detector.DetectorRecognizer.<init>(line:13)
    at com.microblink.entities.recognizers.detector.DetectorRecognizer$1.createFromParcel(line:166)
    at com.microblink.entities.recognizers.detector.DetectorRecognizer$1.createFromParcel(line:162)
    at android.os.Parcel.readParcelable(Parcel.java:2452)
    at android.os.Parcel.readParcelableArray(Parcel.java:2551)
    at com.microblink.entities.recognizers.RecognizerBundle.readFromParcel(line:225)
    at com.microblink.entities.recognizers.RecognizerBundle.<init>(line:220)
    at com.microblink.entities.recognizers.RecognizerBundle.<init>(line:14)
    at com.microblink.entities.recognizers.RecognizerBundle$1.createFromParcel(line:261)
    at com.microblink.entities.recognizers.RecognizerBundle$1.createFromParcel(line:257)
    at com.microblink.intent.IllIIIllII.llIIlIlIIl(line:75)
    at com.microblink.intent.llIIlIlIIl.loadFromIntent(line:81)
    at my_package.DrivingLicenseScannerUtil.getResult(DrivingLicenseScannerUtil.kt:59)
    at my_package.receiver_activity.onActivityResult(BazFragment.java:288)
    at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
    at my_package.receiver_activity.onActivityResult(*.java:121)
    at android.app.Activity.dispatchActivityResult(Activity.java:7193)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4280)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4327)
    at android.app.ActivityThread.-wrap22(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1624)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6523)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
, len = 6
```

I'm using one classifier at the moment to debug the issue. If it helps, here is a code of the classifier:
```Java
public class FooClassifier implements TemplatingClassifier {

  private TemplatingClass mMyTemplatingClass;
  private RegexParser mDocumentNumberParser;
  private ParserParcelization mParcelizedDocumentNumberParser;

  public FooClassifier(
      TemplatingClass mMyTemplatingClass,
      RegexParser mDocumentNumberParser) {
    this.mMyTemplatingClass = mMyTemplatingClass;
    this.mDocumentNumberParser = mDocumentNumberParser;
  }

  private FooClassifier(Parcel in) {
    mParcelizedDocumentNumberParser = ParserParcelization.CREATOR.createFromParcel(in);
  }

  @Override
  public boolean classify(@NonNull TemplatingClass currentClass) {
    RegexParser documentNumberParser;

    if (mMyTemplatingClass == currentClass) {
      documentNumberParser = mDocumentNumberParser;
    } else {
      documentNumberParser = mParcelizedDocumentNumberParser.getParser(currentClass);
    }

    return documentNumberParser.getResult().getResultState() == Parser.Result.State.Valid;
  }

  @Override
  public int describeContents() {
    return 0;
  }

  @Override
  public void writeToParcel(Parcel dest, int flags) {
    if (mDocumentNumberParser != null && mMyTemplatingClass != null) {
      ParserParcelization documentNumberParcelization =
          new ParserParcelization(mDocumentNumberParser, mMyTemplatingClass);
      // we do not need to use writeParcelable because ParserParcelization is not polymorphic
      documentNumberParcelization.writeToParcel(dest, flags);
    }
  }

  public static final Creator<FooClassifier> CREATOR = new Creator<FooClassifier>() {
    @Override
    public FooClassifier createFromParcel(Parcel source) {
      return new FooClassifier(source);
    }

    @Override
    public FooClassifier[] newArray(int size) {
      return new FooClassifier[size];
    }
  };

}
```

### Environment Details

**BlinkID version:** 4.0.0

**Device model:** Google Pixel XL, Huawei Honor 8

**Device Android version:** Android 9.0.0, Android 7.0

**Comment by matvidako** [comment]
Hi Alexander.

I've tried modifying sample app to use your code but can't repro the crash.

Can you show how you're using TemplatingClass.setClassificationProcessorGroups() ?

Also, what IntentDataTransferMode are you using?

**Comment by aednlaxer** [comment]
Hi Matej,

> what IntentDataTransferMode are you using?

Wow, I wasn't using any of them. Adding `IntentDataTransferMode.PERSISTED_OPTIMISED` fixed the issue. Thanks!

**Comment by MauryaAbhishek** [comment]
Bellow method throwing the exception 

mRecognizerBundle.loadFromIntent(getIntent());

lava.lang.IllegalStateException: Expected intent transferable object does not exist in the intent!


Pls help to fix this isssue

**Comment by Brankacro** [comment]
Hello @MauryaAbhishek. 
Can you please let us know how are you setting the license key? Did you follow the steps described [here](https://github.com/BlinkID/blinkid-android#-performing-your-first-scan) and set the license key before using any other classes from the SDK?
Please make sure that the license key is always set before using any method from our SDK, because .onCreate() is always called on application startup.

Also, just to confirm, are you setting up the setIntentDataTransferMode method as below:
https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/BlinkIdSampleApp.kt#L15

If not, please try setting it and let us know how it goes. More info you can find on the following [link
](https://github.com/BlinkID/blinkid-android#-passing-recognizer-objects-between-activities)

Please, let us know if this helped and in case of any questions, feel free to reach out.
Also, you can always reach out to us directly at support@microblink.com.
Best regards.

**Comment by Brankacro** [comment]
Hello @MauryaAbhishek! Hope that the provided info was helpful. Since this topic is inactive, we'll go ahead and close it. In case of any additional questions, feel free to reach out. Also, feel free to contact us directly at support@microblink.com
Best regards.
