### ISSUE TITLE
App crashed while demo version is trying to show a Toast (Android 7.1.1 issue)

### ISSUE THREAD

**Issue by astelmakh** [BlinkID/blinkid-android#154]
### Description

Error reproduced only on API 25 Android 7.1.
We got an error on app start. Error text is the same as described here:

https://stackoverflow.com/questions/51532449/fatal-exception-android-view-windowmanagerbadtokenexception-unable-to-add-wind

Looks like demo version showing toast on app start.

### Environment Details

**BlinkID version:** - 4.8.0

**Device model:** - Nexus 6

**Device Android version:** - 7.1.1

**Device ABI (processor architecture, e.g. ARMv7):** - ARMv7-A

### Log file

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <*>, PID: 23463
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@b3cad44 is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.widget.Toast$TN.handleShow(Toast.java:459)
        at android.widget.Toast$TN$2.handleMessage(Toast.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by i1E** [comment]
Hi @astelmakh,

thank you for the issue report. 

Which UISettings you are using for scanning? 
Can you please share the full error log from the device, like described [here](https://github.com/BlinkID/blinkid-android#other-problems).

**Comment by astelmakh** [comment]
@i1E it crashes on the early stage of the library initialization while `MicroblinkSDK.setLicenseKey(key, this)` in Application class.
Because in case of a demo key library will show a Toast
`Toast.makeText(var0, "Using time-limited license!", 1).show();`

**Comment by i1E** [comment]
Hi @astelmakh,

we will investigate this. 

For now, you can disable that warning Toast by using [`MicroblinkSDK.setShowTimeLimitedLicenseWarning(false)`](https://blinkid.github.io/blinkid-android/com/microblink/MicroblinkSDK.html#setShowTimeLimitedLicenseWarning-boolean-) before setting the license key.

**Comment by astelmakh** [comment]
Thank you !
