### ISSUE TITLE
Error running in my app

### ISSUE THREAD

**Issue by jdruedaq** [BlinkID/blinkid-android#184]
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oneago.logisticsenterprises, PID: 8981
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=Intent { (has extras) }} to activity {com.oneago.logisticsenterprises/com.oneago.logisticsenterprises.activities.BlinkId.BlinkId}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.microblink.fragment.overlay.blinkid.BlinkIdOverlayController$12
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4610)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.microblink.fragment.overlay.blinkid.BlinkIdOverlayController$12
        at android.os.Parcel.readParcelableCreator(Parcel.java:2859)
        at android.os.Parcel.readParcelable(Parcel.java:2781)
        at com.microblink.entities.recognizers.blinkid.generic.BlinkIdRecognizer.readFromParcel(line:248)
        at com.microblink.entities.Entity.<init>(line:38)
        at com.microblink.entities.recognizers.Recognizer.<init>(line:21)
        at com.microblink.entities.recognizers.blinkid.generic.BlinkIdRecognizer.<init>(line:306)
        at com.microblink.entities.recognizers.blinkid.generic.BlinkIdRecognizer.<init>(line:30)
        at com.microblink.entities.recognizers.blinkid.generic.BlinkIdRecognizer$1.createFromParcel(line:312)
        at com.microblink.entities.recognizers.blinkid.generic.BlinkIdRecognizer$1.createFromParcel(line:309)
        at android.os.Parcel.readParcelable(Parcel.java:2790)
        at android.os.Parcel.readParcelableArray(Parcel.java:2889)
        at com.microblink.entities.recognizers.RecognizerBundle.readFromParcel(line:265)
        at com.microblink.entities.recognizers.RecognizerBundle.<init>(line:260)
        at com.microblink.entities.recognizers.RecognizerBundle.<init>(line:17)
        at com.microblink.entities.recognizers.RecognizerBundle$1.createFromParcel(line:302)
        at com.microblink.entities.recognizers.RecognizerBundle$1.createFromParcel(line:298)
        at com.microblink.intent.IllIIIllII.llIIlIlIIl(line:83)
        at com.microblink.intent.llIIlIlIIl.loadFromIntent(line:83)
        at com.oneago.logisticsenterprises.activities.BlinkId.BlinkId.onActivityResult(BlinkId.java:61)
        at android.app.Activity.dispatchActivityResult(Activity.java:7762)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4603)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4652) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) `

**Comment by i1E** [comment]
Hi @jdruedaq,

we need more information. In which way you are using our `BlinkIdOverlayController`? Can you please prepare a minimal sample for reproducing this exception.

**Comment by i1E** [comment]
Hi @jdruedaq, 

we have found where is the problem. To avoid this exception, use `IntentDataTransferMode.PERSISTED_OPTIMISED` for our SDK, you can set it like it is done in [our sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/BlinkIdSampleApp.java#L19).

Thank you for the issue report.

**Comment by jdruedaq** [comment]
> Hi @jdruedaq,
> 
> we have found where is the problem. To avoid this exception, use `IntentDataTransferMode.PERSISTED_OPTIMISED` for our SDK, you can set it like it is done in [our sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/BlinkIdSampleApp.java#L19).
> 
> Thank you for the issue report.

Thanks you, it's works for my
