### ISSUE TITLE
Blink id scan screen crashes for this.

### ISSUE THREAD

**Issue by jolsondc** [BlinkID/blinkid-android#275]
Fatal Exception: java.lang.IllegalStateException: Method must be called after calling start()
       at com.microblink.view.recognition.RecognizerRunnerView.reconfigureRecognizers(RecognizerRunnerView.java:75)
       at com.microblink.fragment.overlay.blinkid.BlinkIdOverlayController.IlIllIlIIl(BlinkIdOverlayController.java:22)
       at com.microblink.fragment.overlay.blinkid.BlinkIdOverlayController.llIIlIlIIl(BlinkIdOverlayController.java)
       at com.microblink.fragment.overlay.blinkid.BlinkIdOverlayController$4.run(BlinkIdOverlayController.java:36)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)atest version of the BlinkID SDK.

**Comment by anjapenic** [comment]
Hi @jolsondc,

Could you please share with us how did you implement the SDK? Also, it would be great if you could sens us a code snippet of your scanning activity.

Best regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
