### ISSUE TITLE
Constantly crashing with demo

### ISSUE THREAD

**Issue by channguyen** [BlinkID/blinkid-android#76]
Hi there, 

I'm testing out the demo custom view and the app constantly crashing with this stacktrace:
I'm running Pixel XL. Also when using `ScanCard` activity directly, with `StrictMode` enabled, I got exception saying `camera.release()` is not being called. Any idea what's happening? Thanks!

```
01-16 19:32:14.158 5109-5621/co.abc.android E/lIlIIlIIll.java:952@Camera2Frame: Failed to capture frame for recognition
                                                                                 java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:665)
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:172)
                                                                                     at com.microblink.secured.lIlIIlIIll.IIIllIlIIl(line:947)
                                                                                     at com.microblink.secured.lIlIIlIIll.llIIlIlIIl(line:1306)
                                                                                     at com.microblink.secured.lIlIIlIIll$2.onImageAvailable(line:1505)
                                                                                     at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at com.microblink.secured.lIlIllllII.run(line:58)
01-16 19:32:14.190 5109-5621/co.abc.android E/lIlIIlIIll.java:952@Camera2Frame: Failed to capture frame for recognition
                                                                                 java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:665)
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:172)
                                                                                     at com.microblink.secured.lIlIIlIIll.IIIllIlIIl(line:947)
                                                                                     at com.microblink.secured.lIlIIlIIll.llIIlIlIIl(line:1306)
                                                                                     at com.microblink.secured.lIlIIlIIll$2.onImageAvailable(line:1505)
                                                                                     at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at com.microblink.secured.lIlIllllII.run(line:58)
01-16 19:32:14.226 5109-5621/co.abc.android E/lIlIIlIIll.java:952@Camera2Frame: Failed to capture frame for recognition
                                                                                 java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:665)
                                                                                     at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:172)
                                                                                     at com.microblink.secured.lIlIIlIIll.IIIllIlIIl(line:947)
                                                                                     at com.microblink.secured.lIlIIlIIll.llIIlIlIIl(line:1306)
                                                                                     at com.microblink.secured.lIlIIlIIll$2.onImageAvailable(line:1505)
                                                                                     at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at com.microblink.secured.lIlIllllII.run(line:58)
01-16 19:32:14.320 5109-5620/co.abc.android E/lIlIIIIlIl.java:92@Camera2Control: unable to register accelerometer sensor with sample period 19565 microseconds. Trying SENSOR_DELAY_NORMAL...
01-16 19:32:14.321 5109-5620/co.abc.android W/lIlIIIIlIl.java:96@Camera2Control: unable to register accelerometer sensor at all.  

```

**Comment by DoDoENT** [comment]
Hi! Thank you for your report. We haven't seen that crash before, so it may be specific to Pixel XL device. Can you reproduce it on some other android device? Also, which version of BlinkID are you using?

**Comment by casidiablo** [comment]
I'm also getting the same error in a Pixel (first generation). I'm running BlinkId 4.1.0.

**Comment by casidiablo** [comment]
By the way, in my case, it only happens with the `MrtdRecognizer`. USDL recognizer seems to work.

**Comment by SandraKuzmic** [comment]
Hi, unfortunately, we don't have this device in our office currently. We should probably get it in a couple of days and then we will try to reproduce the crash and contact you.

**Comment by casidiablo** [comment]
Hello Sandra.

I figured in my case it was crashing because of something unrelated to Microblink SDK itself.
